# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('contents', models.CharField(default=b'', max_length=1000)),
                ('path', models.CharField(default=b'', max_length=1000)),
            ],
        ),
    ]
